version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./:/code"
    links:
      - "db:db"
    depends_on:
      - db

  db:
    image: postgres:14.4
    environment:
      - "POSTGRES_USER=dbuser"
      - "POSTGRES_PASSWORD=dbpass2022"
      - "POSTGRES_DB=testdb"
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
