version: '3'
services:
  app:
    image: node-docker:1.3
    ports:
      - "3000:3000"
    volumes:
      - "./:/code"
    links:
      - "db:db"
    depends_on:
      - db
    networks:
      - app
    deploy:
      replicas: 3
      # allow 3 instances of service to be deployed

  db:
    image: postgres:14.4
    env_file:
      - ./db/.env.db
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql" 
    networks:
      - app
    deploy:
      replicas: 2

  viz:
    image: dockersamples/visualizer
    ports: 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app
networks:
  app:      
  # told the Docker swarm to create a network named app so that it can be used by the services.
